import { Link } from 'wouter';
import { ArrowRight, MapPin, ShieldCheck } from 'lucide-react';
import { ComingSoon, PropertyCard, SearchPanel, SectionHeading, SiteFooter, SiteNav, StateShowcase } from '@/components/staykolo-ui';

const areas = ['Koramangala', 'HSR Layout', 'Indiranagar', 'Whitefield', 'Bellandur', 'Yeshwanthpur'];

export function Home() {
  return <div className="min-h-[100dvh] bg-[#fbfcfd]">
    <SiteNav />
    <main>
      <section className="border-b border-[#dfe9ee] bg-[#edf7fa]">
        <div className="sk-container grid min-h-[525px] items-center gap-10 py-16 lg:grid-cols-[1.03fr_.97fr] lg:py-20">
          <div><p className="sk-eyebrow">PG accommodation, made clearer</p><h1 className="sk-display mt-4 max-w-[620px] text-[42px] font-extrabold leading-[1.08] text-[#18364a] sm:text-[56px]">Find a place that is <span className="text-[#0878b0]">run well.</span></h1><p className="mt-5 max-w-[510px] text-[16px] leading-7 text-[#59717e]">Search well-managed PGs in Bengaluru with the details you need to decide with confidence.</p><div className="mt-8 flex flex-wrap items-center gap-3"><Link href="/search" className="sk-button sk-button-primary" data-testid="link-hero-search">Browse available PGs <ArrowRight size={16} /></Link><Link href="/about" className="sk-button sk-button-secondary" data-testid="link-hero-how-it-works">How Staykolo works</Link></div><div className="mt-8 flex items-center gap-2 text-[12px] font-medium text-[#607b88]"><ShieldCheck size={16} className="text-[#168aad]" /> Clear listings. Direct decisions. No inflated claims.</div></div>
          <div className="sk-grid-paper relative rounded-[18px] border border-[#c7e0e7] p-4 sm:p-7"><div className="rounded-xl border border-[#d1e1e6] bg-white p-5 shadow-[0_10px_25px_rgba(28,65,87,.08)]"><div className="flex items-center justify-between border-b border-[#ebf0f2] pb-4"><div><p className="text-[11px] font-bold uppercase tracking-[.12em] text-[#84959e]">Bengaluru</p><p className="sk-display mt-1 text-[18px] font-bold text-[#18364a]">Your next address</p></div><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#e4f4f7] text-[#0878b0]"><MapPin size={18} /></div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-lg bg-[#f4f8f9] p-3"><p className="text-[11px] text-[#81909a]">Properties to compare</p><p className="sk-mono mt-2 text-[20px] font-bold text-[#18364a]">01–24</p></div><div className="rounded-lg bg-[#f4f8f9] p-3"><p className="text-[11px] text-[#81909a]">Search by</p><p className="mt-2 text-[14px] font-bold text-[#18364a]">Area + needs</p></div></div><div className="mt-4 space-y-2"><div className="flex items-center justify-between rounded-lg border border-[#e4ebee] px-3 py-3"><span className="text-[12px] font-semibold text-[#46616e]">Liveability details</span><span className="text-[11px] text-[#168aad]">Included</span></div><div className="flex items-center justify-between rounded-lg border border-[#e4ebee] px-3 py-3"><span className="text-[12px] font-semibold text-[#46616e]">Property management</span><span className="text-[11px] text-[#168aad]">Included</span></div></div></div><p className="mt-4 text-center text-[11px] font-medium text-[#6b8793]">A considered start to your Bengaluru search</p></div>
        </div>
      </section>
      <section className="relative z-10 -mt-9"><div className="sk-container"><SearchPanel /></div></section>
      <section className="sk-container py-20"><SectionHeading eyebrow="Start with your area" title="Bengaluru, by neighbourhood" copy="Begin with the part of the city that fits your commute and routine." /><div className="mt-7 flex flex-wrap gap-2">{areas.map((area) => <Link href="/search" key={area} className="inline-flex items-center gap-2 rounded-full border border-[#d7e4e9] bg-white px-4 py-2.5 text-[13px] font-semibold text-[#46616e] transition-colors hover:border-[#7ebdce] hover:bg-[#edf8fa] hover:text-[#0878b0]" data-testid={`link-area-${area.toLowerCase().replaceAll(' ', '-')}`}><MapPin size={14} className="text-[#168aad]" />{area}</Link>)}</div></section>
      <section className="border-y border-[#e1e9ed] bg-white"><div className="sk-container py-20"><SectionHeading eyebrow="A better shortlist" title="Details before decisions" copy="A useful property profile should answer practical questions before you book a visit." action={<Link href="/search" className="sk-button sk-button-secondary" data-testid="link-view-all-properties">Explore properties <ArrowRight size={15} /></Link>} /><div className="mt-8 grid gap-5 md:grid-cols-3"><PropertyCard name="Orchid House" area="HSR Layout" rooms="Private & shared rooms" price="₹14,500" tag="Managed stay" tone="blue" /><PropertyCard name="Northstar Living" area="Yeshwanthpur" rooms="Private rooms" price="₹12,800" tag="Recently verified" tone="cyan" /><PropertyCard name="Mango Tree Homes" area="Koramangala" rooms="Shared rooms" price="₹10,900" tag="Good for first move" tone="slate" /></div></div></section>
      <section className="sk-container py-20"><div className="grid gap-5 md:grid-cols-3"><div className="md:col-span-2 sk-surface-blue rounded-[14px] p-7 sm:p-9"><p className="sk-eyebrow">For property owners and operators</p><h2 className="sk-display mt-3 max-w-[540px] text-[28px] font-bold leading-tight text-[#18364a]">Keep your property information as clear as the place itself.</h2><p className="mt-3 max-w-[560px] text-[14px] leading-6 text-[#5f7783]">Staykolo gives well-run PGs a straightforward way to present their property, answer practical questions, and meet the right residents.</p><Link href="/contact" className="sk-button sk-button-primary mt-6" data-testid="link-owner-contact">Talk to our property team <ArrowRight size={16} /></Link></div><div className="sk-card flex flex-col justify-between p-7"><div><p className="sk-eyebrow">Staykolo note</p><h2 className="sk-display mt-3 text-[22px] font-bold leading-tight text-[#18364a]">The city is easier to navigate when the details are honest.</h2></div><Link href="/chronicles" className="mt-7 inline-flex items-center gap-2 text-[13px] font-bold text-[#0878b0]" data-testid="link-read-chronicles">Read the chronicles <ArrowRight size={15} /></Link></div></div></section>
      <StateShowcase />
    </main>
    <SiteFooter />
  </div>;
}

export function FutureScreen({ title }: { title: string }) {
  return <div className="min-h-[100dvh] bg-[#fbfcfd]"><SiteNav /><ComingSoon title={title} /><SiteFooter /></div>;
}